*.class: src/edu/rutgers/rl3/comp/*.java
	javac -source 5 -cp /home/shiwali/soar/SoarSuite/out/share/java/sml.jar:/home/shiwali/infiniteMario/system/libraries/rl-viz/RLVizLib.jar   -d bin src/edu/rutgers/rl3/comp/*.java

clean:
	rm -Rf bin/*
